
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TOSHIBA
 */
public class MainPage extends javax.swing.JFrame {
    
    MainPageIslemleri islemler = new MainPageIslemleri();
    
    DefaultTableModel tModel;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
        tModel = (DefaultTableModel)table1.getModel();
        calisanGoruntule();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Ad = new javax.swing.JTextField();
        txt_Soyad = new javax.swing.JTextField();
        txt_Departman = new javax.swing.JTextField();
        txt_Maas = new javax.swing.JTextField();
        btn_Ekle = new javax.swing.JButton();
        btn_Guncelle = new javax.swing.JButton();
        btn_Sil = new javax.swing.JButton();
        txt_arama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Page");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        table1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ad", "Soyad", "Departman", "Maas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setResizable(false);
            table1.getColumnModel().getColumn(1).setResizable(false);
            table1.getColumnModel().getColumn(2).setResizable(false);
            table1.getColumnModel().getColumn(3).setResizable(false);
            table1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ad :");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad :");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Departman :");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Maaş :");

        txt_Ad.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N

        txt_Soyad.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N

        txt_Departman.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N

        txt_Maas.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N

        btn_Ekle.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        btn_Ekle.setText("Ekle");
        btn_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EkleActionPerformed(evt);
            }
        });

        btn_Guncelle.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });

        btn_Sil.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        btn_Sil.setText("Sil");
        btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SilActionPerformed(evt);
            }
        });

        txt_arama.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        txt_arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_aramaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arama :");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/emp.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Ad)
                                    .addComponent(txt_Soyad)
                                    .addComponent(txt_Departman)
                                    .addComponent(txt_Maas, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(162, 162, 162)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_arama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_Soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_Departman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_Maas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btn_Ekle)
                                .addGap(20, 20, 20)
                                .addComponent(btn_Guncelle)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Sil))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_aramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_aramaKeyReleased
        // TODO add your handling code here:
        
        String ara = txt_arama.getText();
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tModel);
        table1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }//GEN-LAST:event_txt_aramaKeyReleased

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        
        if(txt_arama.getText().equals("")) {
            
            int seciliRow = table1.getSelectedRow();
        
            txt_Ad.setText(tModel.getValueAt(seciliRow, 1).toString());
            txt_Soyad.setText(tModel.getValueAt(seciliRow, 2).toString());
            txt_Departman.setText(tModel.getValueAt(seciliRow, 3).toString());
            txt_Maas.setText(tModel.getValueAt(seciliRow, 4).toString());
            
        }
        
    }//GEN-LAST:event_table1MouseClicked

    private void btn_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EkleActionPerformed
        // TODO add your handling code here:
        
        String ad = txt_Ad.getText();
        String soyad = txt_Soyad.getText();
        String departman = txt_Departman.getText();
        String yaziylaMaas = txt_Maas.getText();
        
        if(ad.equals("") || soyad.equals("") || departman.equals("") || yaziylaMaas.equals("")) {
            JOptionPane.showMessageDialog(this, "Tüm Verileri Girdikten Sonra Ekleme Yapabilirsiniz!");
        }
        else {
            int maas = Integer.parseInt(txt_Maas.getText());
            islemler.veriEkle(ad, soyad, departman, maas);
            JOptionPane.showMessageDialog(this, ad + " Isimli Çalışan Sisteme Kaydedilmiştir!");
        }
        
        calisanGoruntule();
        
    }//GEN-LAST:event_btn_EkleActionPerformed

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        // TODO add your handling code here:
        
        String ad = txt_Ad.getText();
        String soyad = txt_Soyad.getText();
        String departman = txt_Departman.getText();
        String yaziylaMaas = txt_Maas.getText();
        
        int secilenSatir = table1.getSelectedRow();
        
        if(secilenSatir == -1) {
            JOptionPane.showMessageDialog(this, "Bir Veri Secmeden Guncelleme Yapamazsiniz!");
        }
        else {
            int id = Integer.parseInt(tModel.getValueAt(secilenSatir, 0).toString());
            
            if(ad.equals("") || soyad.equals("") || departman.equals("") || yaziylaMaas.equals("")) {
                JOptionPane.showMessageDialog(this, "Tüm Verileri Girdikten Sonra Güncelleme Yapabilirsiniz!");
            }
            else {
                int maas = Integer.parseInt(txt_Maas.getText());
                islemler.veriGuncelle(id, ad, soyad, departman, maas);
                JOptionPane.showMessageDialog(this, ad + " Isimli Çalışan Sistemde Güncellenmiştir!");
            }
        }
        
        calisanGoruntule();
        
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    private void btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SilActionPerformed
        // TODO add your handling code here:
        
        int secilenSatir = table1.getSelectedRow();
        
        if(secilenSatir == -1) {
            JOptionPane.showMessageDialog(this, "Bir Veri Secmeden Silme Islemi Yapamazsiniz!");
        }
        else {
            
            int id = Integer.parseInt(tModel.getValueAt(secilenSatir, 0).toString());
            
            islemler.veriSil(id);
            
            JOptionPane.showMessageDialog(this, id + " Numaralı Çalışan Sistemden Silinmiştir!");
            
        }
        
        calisanGoruntule();
        
    }//GEN-LAST:event_btn_SilActionPerformed

    public void calisanGoruntule() {
        
        tModel.setRowCount(0);
        
        ResultSet veriler = islemler.veriCek();
        
        try {
            
            while(veriler.next()) {
                
                int id = veriler.getInt("id");
                String ad = veriler.getString("ad");
                String soyad = veriler.getString("soyad");
                String departman = veriler.getString("departman");
                int maas = veriler.getInt("maas");
                
                Object[] tabloSatiri = {String.valueOf(id), ad, soyad, departman, String.valueOf(maas)};
                tModel.addRow(tabloSatiri);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ekle;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_Sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txt_Ad;
    private javax.swing.JTextField txt_Departman;
    private javax.swing.JTextField txt_Maas;
    private javax.swing.JTextField txt_Soyad;
    private javax.swing.JTextField txt_arama;
    // End of variables declaration//GEN-END:variables
}
